# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cuoiki.xdc

# Block Designs: bd/cuoiki/cuoiki.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki || ORIG_REF_NAME==cuoiki} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_microblaze_0_0/cuoiki_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_microblaze_0_0 || ORIG_REF_NAME==cuoiki_microblaze_0_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_dlmb_v10_0/cuoiki_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_dlmb_v10_0 || ORIG_REF_NAME==cuoiki_dlmb_v10_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_ilmb_v10_0/cuoiki_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_ilmb_v10_0 || ORIG_REF_NAME==cuoiki_ilmb_v10_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_dlmb_bram_if_cntlr_0/cuoiki_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==cuoiki_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_ilmb_bram_if_cntlr_0/cuoiki_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==cuoiki_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_lmb_bram_0/cuoiki_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_lmb_bram_0 || ORIG_REF_NAME==cuoiki_lmb_bram_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_mdm_1_0/cuoiki_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_mdm_1_0 || ORIG_REF_NAME==cuoiki_mdm_1_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_clk_wiz_1_0/cuoiki_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_clk_wiz_1_0 || ORIG_REF_NAME==cuoiki_clk_wiz_1_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_rst_clk_wiz_1_100M_0/cuoiki_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==cuoiki_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_axi_uartlite_0_0/cuoiki_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_axi_uartlite_0_0 || ORIG_REF_NAME==cuoiki_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_xbar_0/cuoiki_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_xbar_0 || ORIG_REF_NAME==cuoiki_xbar_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_microblaze_0_axi_periph_0/cuoiki_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_microblaze_0_axi_periph_0 || ORIG_REF_NAME==cuoiki_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_axi_gpio_0_0/cuoiki_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_axi_gpio_0_0 || ORIG_REF_NAME==cuoiki_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_present_ctr_0_4/cuoiki_present_ctr_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_present_ctr_0_4 || ORIG_REF_NAME==cuoiki_present_ctr_0_4} -quiet] -quiet

# IP: bd/cuoiki/ip/cuoiki_axi_uartlite_1_0/cuoiki_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cuoiki_axi_uartlite_1_0 || ORIG_REF_NAME==cuoiki_axi_uartlite_1_0} -quiet] -quiet

# XDC: c:/Users/S88 Service/Desktop/vivado_nhng/ednacuoiki/ednacuoiki.gen/sources_1/bd/cuoiki/cuoiki_ooc.xdc
