set_property SRC_FILE_INFO {cfile:{C:/Users/S88 Service/Desktop/vivado_nhng/ednacuoiki/ednacuoiki.srcs/constrs_1/new/cuoiki.xdc} rfile:../../../ednacuoiki.srcs/constrs_1/new/cuoiki.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports {GPIO_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports rx_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports tx_0]
