# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/S88 Service/Desktop/vivado_nhng/ednacuoiki/ednacuoiki.srcs/sources_1/bd/cuoiki/ip/cuoiki_dlmb_v10_0/cuoiki_dlmb_v10_0.xci
# IP: The module: 'cuoiki_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/S88 Service/Desktop/vivado_nhng/ednacuoiki/ednacuoiki.gen/sources_1/bd/cuoiki/ip/cuoiki_dlmb_v10_0/cuoiki_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cuoiki_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/S88 Service/Desktop/vivado_nhng/ednacuoiki/ednacuoiki.srcs/sources_1/bd/cuoiki/ip/cuoiki_dlmb_v10_0/cuoiki_dlmb_v10_0.xci
# IP: The module: 'cuoiki_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/S88 Service/Desktop/vivado_nhng/ednacuoiki/ednacuoiki.gen/sources_1/bd/cuoiki/ip/cuoiki_dlmb_v10_0/cuoiki_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cuoiki_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
